title: "Sankha Narayan Guria"
baseurl: ""

date_format: "%Y-%m-%d"

google_analytics: "UA-42948095-1"
disqus_shortname:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
